image: gradle:6.0-jdk13

stages:
  - build
  - validate
  - test

variables:
  # Disable the Gradle daemon to ensure isolated runs of the CI pipeline.
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

build:
  stage: build
  script:
    - echo "BUILDING SERVER" 
    - cd server
    - gradle --build-cache assemble
    - cd ..
    - echo "BUILDING CLIENT"
    - cd template
    - gradle --build-cache assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build/
      - .gradle/

checkStyle:
  stage: validate
  script:
    - echo "checkStyle SERVER"
    - cd server
    - gradle checkstyleMain checkstyleTest
    - echp "checkStyle CLIENT"
    - cd ..
    - cd template
    - gradle checkstyleMain checkstyleTest
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build/
      - .gradle/

spotBugs:
  stage: validate
  script:
    - echo "SPOTBUGS SERVER"
    - cd server
    - gradle spotbugsMain spotbugsTest
    - cd ..
    - cd template
    - echo "SPOTBUGS CLIENT"
    - gradle spotbugsMain sputbugsTest
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build/
      - .gradle/

PMD:
  stage: validate
  script:
    - ECHO "PMD SERVER"
    - cd server
    - gradle pmdMain pmdTest
    - cd ..
    - cd template
    - echo "PMD CLient"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build/
      - .gradle/

test:
  stage: test
  script:
    - echo "TEST SERVER"
    - cd server
    - gradle check
    - cd ..
    - cd template
    - echo "TEST CLIENT"
    - gradle check
